TOKEN = ""
EMAIL = "github@gmail.com"
TABLE_TOKEN_FILE = "table_token.json"
COMMISSION = 0.0005
UNARY_REQUEST_LIMIT = 100
MAX_REQUEST_ATTEMPTS = 50
LOGGING_LEVEL = "DEBUG"  # DEBUG / INFO / WARNING / ERROR / CRITICAL
